version: "3.8"

services:
  # Development Services
  frontend-dev:
    build:
      context: ./frontend
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    env_file:
      - ./frontend/.env.local
    environment:
      - NODE_ENV=development
    profiles:
      - dev
    depends_on:
      - backend-dev

  backend-dev:
    build:
      context: ./backend
      target: development
    ports:
      - "8080:8080"
    volumes:
      - ./backend/src:/app/src
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=development
    profiles:
      - dev

  # Production Services
  frontend-prod:
    build:
      context: ./frontend
      target: production
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env.production
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    profiles:
      - prod
    depends_on:
      - backend-prod

  backend-prod:
    build:
      context: ./backend
      target: production
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env.production
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:8080/api/v1/users/me",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
    profiles:
      - prod
